# Ansible Zabbix external inventory script settings
#

[zabbix]

# Server location
server = http://zabbix.local

# Login
username = API
#password = zabbix

# Authentication token, if empty then username/password used to authenticate
auth_token = d6f2595b3b4bbd99814b376c2549962ab2b43c607d894a9f584a638b3dec2b21

# Verify the server's SSL certificate
validate_certs = True

# Time to wait for API response
tiemout = 30

# Read zabbix inventory per host
read_host_inventory = True

# Set ansible_ssh_host based on first interface settings
use_host_interface = True
